# render.yaml - Configuração para Django + Poetry
services:
  - type: web
    name: ecotech-django  # Substitua pelo nome do seu serviço
    runtime: python
    pythonVersion: "3.11.11"  # Mesma versão dos seus logs
    buildCommand: |
      python -m pip install --upgrade pip
      pip install poetry
      poetry install --only main --no-interaction --no-root
      poetry export -f requirements.txt --output requirements.txt --without-hashes
    startCommand: |
      python manage.py migrate
      gunicorn seu_projeto.wsgi:application --workers 4
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: seu_projeto.settings.production  # Ajuste para seu módulo
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DEBUG
        value: "False"
    healthCheckPath: /health-check/  # Rota simples para verificar se o app está vivo

# Se precisar de banco de dados PostgreSQL (descomente abaixo)
# databases:
#   - name: ecotech_db
#     databaseName: ecotech
#     user: ecotech_user
#     plan: free